//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practich3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sborka
    {
        public int IdComputer { get; set; }
        public int IdProduct { get; set; }
        public int Quant { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
