//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practich3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int IdEmp { get; set; }
        [Required(ErrorMessage = "Поле Логин не должно быть пустым")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Поле Логин слишком длинное, должен быть в диапазоне {1}-{2}")]
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Employeey Employeey { get; set; }
    }
}
